version: '3'
services:
  app:
    env_file: .env.example
    build:
      context: .
    ports:
      - "8080:8080"
  db:
    env_file: .env.example
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    volumes:
      - ./postgres/*.sql /docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

